### ISSUE TITLE
File Creation: Check if the user entered a extension and if no add one.

### ISSUE THREAD

**Issue by RebelCoderJames** [RebelCoderJames/console-windows-notes-editor#12]

**Comment by GrowingCash322** [comment]
Hier ist noch die file creation code also es checkt ob man .txt geschrieben hat und wann es nicht geschrieben hat es schreibt es automatisch also es will immer wie .txt datai speichern.


using System;
using System.IO;

class Program
{
    static void Main()
    {
        Console.WriteLine("Geben Sie den Dateinamen ein (ohne Erweiterung):");
        string fileName = Console.ReadLine();

        Console.WriteLine("Geben Sie die Dateierweiterung ein (ohne Punkt), oder lassen Sie es leer:");
        string fileExtension = Console.ReadLine();

        // Füge eine Standarderweiterung ".txt" hinzu, wenn keine eingegeben wurde
        if (string.IsNullOrEmpty(fileExtension))
        {
            fileExtension = "txt";
        }

        string fullFileName = fileName + "." + fileExtension;

        // Überprüfe, ob die Datei bereits existiert
        if (File.Exists(fullFileName))
        {
            Console.WriteLine("Die Datei existiert bereits.");
        }
        else
        {
            // Erstelle die Datei
            File.Create(fullFileName);
            Console.WriteLine($"Die Datei '{fullFileName}' wurde erstellt.");
        }
    }
}
