### ISSUE TITLE
create notes encyrption (password)

### ISSUE THREAD

**Issue by bettercallmilan** [RebelCoderJames/console-windows-notes-editor#3]

**Comment by RebelCoderJames** [comment]
See: https://github.com/RebelCoderJames/console-windows-file-explorer/blob/v3/Windows%20Terminal%20File%20Explorer/Windows%20Terminal%20File%20Explorer/crypt.cs

**Comment by RebelCoderJames** [comment]
Needs:
-When opening Files: Dedecting and decrypting the encrypted file
-When saving: When it is an encrypted file encrypt it with the new contents again.

You can use:
crypt.Encrypt(byte of file, password)
crypt.Decrypt(byte of file, password)

Needs:
-File Manager to open files https://github.com/RebelCoderJames/console-windows-notes-editor/issues/4

**Comment by RebelCoderJames** [comment]
This can now be started working on.
