### ISSUE TITLE
Better Layout for welcome screen

### ISSUE THREAD

**Issue by RebelCoderJames** [RebelCoderJames/console-windows-notes-editor#7]
So it aligns, and show recently accessed files. And Colors

**Comment by RebelCoderJames** [comment]
@GrowingCash322 Can you do this? Please make a design first and show it here before implementing.

**Comment by RebelCoderJames** [comment]
![image](https://github.com/RebelCoderJames/console-windows-notes-editor/assets/142885453/6780a21f-d6f5-4470-9d00-1c6892b81a29)

**Comment by RebelCoderJames** [comment]
Like that

**Comment by RebelCoderJames** [comment]
@bettercallmilan Removed the while do loop. it now updates when ever you give an input. i think this can be closed?

**Comment by bettercallmilan** [comment]
welcome screen is now in the middle and aligns when window size changed. thus this issue is closed
